# Generated by Django 4.2.25 on 2025-10-03 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_question_question_type_participation_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='survey',
            name='valid_since',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 3, 22, 44, 45, 398660, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 3, 22, 45, 0, 900182, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
