# Generated by Django 4.2.25 on 2025-10-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_choice_created_at_remove_choice_updated_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('survey', 'user_id'), name='unique_participation_per_user'),
        ),
    ]
